services:
  app:
    container_name: sis-dev
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    command: tail -f /dev/null
    volumes:
      - .:/app # BIND MOUNT    
    networks:
      - student_net
    working_dir: /app
    depends_on:
      - db
    environment:
      POSTGRES_HOST: db
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    stdin_open: true
    tty: true                   

  db:
    image: postgres:18.1
    container_name: postgres-dev
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata_dev:/var/lib/postgresql
      - ./db/init:/docker-entrypoint-initdb.d
    networks:
      - student_net

volumes:
  pgdata_dev:


networks:
  student_net:
    driver: bridge