name: C++ Docker CI

on:
  push:
    branches: [ "main","develop" ]
  pull_request:
    branches: [ "main","develop" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Set up Docker (already installed on runner, this enables Buildx)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3. Build Docker image
      - name: Build Docker image
        run: |
          docker build -t student-information-system-app .

      # 4. Success message (optional but nice for grading)
      - name: Build finished
        run: echo "Docker image built successfully"
